// Copyright 2019-2020 CERN and copyright holders of ALICE O2.
// See https://alice-o2.web.cern.ch/copyright for details of the copyright holders.
// All rights not expressly granted are reserved.
//
// This software is distributed under the terms of the GNU General Public
// License v3 (GPL Version 3), copied verbatim in the file "COPYING".
//
// In applying this license CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

#include "InfoLoggerClient.h"

int main()
{

  try {
    InfoLoggerClient cl;

    int i = 0;
    char buffer[1024];
    int len;
    //  len=snprintf(buffer,sizeof(buffer),"test message %d AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC\n",i);
    //  len=snprintf(buffer,sizeof(buffer),"test message %d AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC\n",i);
    //  len=10;
    //  printf("message length = %d bytes\n",len);
    for (i = 0; i < 10; i++) {
      //len=strlen(buffer);
      len = snprintf(buffer, sizeof(buffer), "test message %d\n", i);
      if (cl.send(buffer, len)) {
        throw __LINE__;
      }
    }
  }

  catch (int errCode) {
  }

  return 0;
}

