#include "InfoLoggerClient.h"



int main() {

  try {
    InfoLoggerClient cl;
    
    int i=0;
    char buffer[1024];
    int len;
    //  len=snprintf(buffer,sizeof(buffer),"test message %d AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC\n",i);  
    //  len=snprintf(buffer,sizeof(buffer),"test message %d AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC AAAAAAAAAABBBBBBBBBCCCCCCCCCC\n",i);  
    //  len=10;
    //  printf("message length = %d bytes\n",len);
    for (i=0;i<10;i++) {
      //len=strlen(buffer);
      len=snprintf(buffer,sizeof(buffer),"test message %d\n",i);
      if (cl.send(buffer,len)) {
        throw __LINE__;
      }
    }
  }
  
  catch (int errCode) {
  }
 
  return 0;
}
